# Generated by Django 5.2 on 2025-09-30 19:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoyaltyProgram",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("points", models.IntegerField(default=0)),
                ("visits", models.IntegerField(default=0)),
                ("last_visit", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_programs",
                        to="users.profile",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_loyalty_programs",
                        to="users.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loyalty Program",
                "verbose_name_plural": "Loyalty Programs",
                "indexes": [
                    models.Index(
                        fields=["client"], name="notificatio_client__501260_idx"
                    ),
                    models.Index(
                        fields=["provider"], name="notificatio_provide_923a12_idx"
                    ),
                ],
                "unique_together": {("client", "provider")},
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("appointment_reminder", "Appointment Reminder"),
                            ("payment_confirmation", "Payment Confirmation"),
                            ("booking_confirmation", "Booking Confirmation"),
                            ("review_request", "Review Request"),
                            ("promotional", "Promotional"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                (
                    "related_entity_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "related_entity_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "indexes": [
                    models.Index(
                        fields=["user"], name="notificatio_user_id_c291d5_idx"
                    ),
                    models.Index(
                        fields=["is_read"], name="notificatio_is_read_9edb86_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="notificatio_created_46ad24_idx"
                    ),
                ],
            },
        ),
    ]
