# Generated by Django 5.2 on 2025-09-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="message_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="message_fr",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="title_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="title_fr",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
