# Generated by Django 5.2 on 2025-09-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="about_me_en",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="About me"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="about_me_fr",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="About me"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="description_fr",
            field=models.TextField(blank=True, null=True),
        ),
    ]
