# Generated by Django 5.2 on 2025-09-15 09:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="is_verified_landlord",
        ),
    ]
