# Generated by Django 5.2 on 2025-09-30 23:28

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_profile_about_me_en_profile_about_me_fr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+237670181440",
                max_length=30,
                region=None,
                verbose_name="Phone Number",
            ),
        ),
    ]
