# Generated by Django 5.2 on 2025-10-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_profile_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="provider_application_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="provider_application_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="provider_application_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("withdrawn", "Withdrawn"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="withdrawn_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
