# Generated by Django 5.2 on 2025-10-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_profile_provider_application_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="availability_schedule",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="certifications",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="emergency_contact",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="portfolio_urls",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="service_categories",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="years_of_experience",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["provider_application_status"],
                name="users_profi_provide_171952_idx",
            ),
        ),
    ]
