# Generated by Django 5.2 on 2025-10-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_profile_availability_schedule_profile_certifications_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="availability_schedule_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="availability_schedule_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="business_address_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="business_address_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="business_name_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="business_name_fr",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
