# Generated by Django 5.2 on 2025-09-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="provideravailabilityexception",
            name="reason_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="provideravailabilityexception",
            name="reason_fr",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
