# Generated by Django 5.2 on 2025-09-16 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("services", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="services.service"
            ),
        ),
        migrations.AddField(
            model_name="appointmentslot",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="appointments.appointment",
            ),
        ),
        migrations.AddField(
            model_name="appointmentslot",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slots",
                to="users.profile",
            ),
        ),
        migrations.AddField(
            model_name="provideravailability",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availabilities",
                to="users.profile",
            ),
        ),
        migrations.AddField(
            model_name="provideravailabilityexception",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availability_exceptions",
                to="users.profile",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["client"], name="appointment_client__1de7de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["provider"], name="appointment_provide_59b198_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["status"], name="appointment_status_8fe9d7_idx"),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["payment_status"], name="appointment_payment_79f9ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["scheduled_for"], name="appointment_schedul_fa8dbb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentslot",
            index=models.Index(
                fields=["provider"], name="appointment_provide_f83fb3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentslot",
            index=models.Index(
                fields=["slot_start", "slot_end"], name="appointment_slot_st_bfb101_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentslot",
            index=models.Index(fields=["status"], name="appointment_status_13c317_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="appointmentslot",
            unique_together={("provider", "slot_start")},
        ),
        migrations.AddIndex(
            model_name="provideravailability",
            index=models.Index(
                fields=["provider", "day_of_week"],
                name="appointment_provide_a02f3d_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="provideravailability",
            unique_together={("provider", "day_of_week")},
        ),
        migrations.AddIndex(
            model_name="provideravailabilityexception",
            index=models.Index(
                fields=["provider", "exception_date"],
                name="appointment_provide_67c20e_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="provideravailabilityexception",
            unique_together={("provider", "exception_date")},
        ),
    ]
