# Generated by Django 5.2 on 2025-10-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_service_description_en_service_description_fr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicecategory",
            name="image_url",
            field=models.ImageField(
                default="categories/service_category.png",
                upload_to="",
                verbose_name="Image",
            ),
        ),
    ]
