# Generated by Django 5.2 on 2025-09-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="admin_notes_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="admin_notes_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="reason_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="reason_fr",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="comment_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="comment_fr",
            field=models.TextField(blank=True, null=True),
        ),
    ]
