# Generated by Django 5.2 on 2025-09-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="escrow_release_trigger_en",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="escrow_release_trigger_fr",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
